export const PLUGIN_MANAGEMENT_CHANNELS = {
	LIST: "origin:plugins:list",
	LIST_ALL: "origin:plugins:list-all",
	INSTALL_FROM_ARCHIVE: "origin:plugins:install-from-archive",
	INSTALL_FROM_URL: "origin:plugins:install-from-url",
	INSTALL_FROM_PATH: "origin:plugins:install-from-path",
	REGISTER_MODE_GATE: "origin:plugins:register-mode-gate",
	SET_CONTRIBUTION_MODE: "origin:plugins:set-contribution-mode",
	UNINSTALL: "origin:plugins:uninstall",
	SET_ENABLED: "origin:plugins:set-enabled",
	GRANT_PERMISSIONS: "origin:plugins:grant-permissions",
	REVOKE_PERMISSIONS: "origin:plugins:revoke-permissions",
	GRANT_COMMANDS: "origin:plugins:grant-commands",
	REVOKE_COMMANDS: "origin:plugins:revoke-commands",
	APPLY_SETUP: "origin:plugins:apply-setup",
	RELOAD: "origin:plugins:reload",
	DEV_WATCH_START: "origin:plugins:dev-watch-start",
	DEV_WATCH_STOP: "origin:plugins:dev-watch-stop",
} as const;

export const PLUGIN_EXECUTION_CHANNELS = {
	COMMAND_RUN: "origin:plugins:command-run",
	COMMAND_SPAWN: "origin:plugins:command-spawn",
	COMMAND_SPAWN_STOP: "origin:plugins:command-spawn-stop",
	COMMAND_SPAWN_STATUS: "origin:plugins:command-spawn-status",
	COMMAND_SPAWN_EXIT: "origin:plugins:command-spawn-exit",
	CLI_PROVIDER_STATUS_GET: "origin:plugins:cli-provider:status-get",
	CLI_PROVIDER_STATUS: "origin:plugins:cli-provider:status",
	CLI_PROVIDER_RETRY: "origin:plugins:cli-provider:retry",
	CLI_PROVIDER_RUN: "origin:plugins:cli-provider:run",
	CLI_PROVIDER_SPAWN: "origin:plugins:cli-provider:spawn",
	CLI_PROVIDER_SPAWN_STOP: "origin:plugins:cli-provider:spawn-stop",
	CLI_PROVIDER_SPAWN_STATUS: "origin:plugins:cli-provider:spawn-status",
	CLI_PROVIDER_SPAWN_EXIT: "origin:plugins:cli-provider:spawn-exit",
	SERVICE_STATUS_GET: "origin:plugins:service:status-get",
	SERVICE_STATUS: "origin:plugins:service:status",
	SERVICE_PLATFORM_GET: "origin:plugins:service:platform-get",
	SERVICE_INSTALL: "origin:plugins:service:install",
	SERVICE_START: "origin:plugins:service:start",
	SERVICE_STOP: "origin:plugins:service:stop",
	SERVICE_RESTART: "origin:plugins:service:restart",
	SERVICE_CONNECTION: "origin:plugins:service:connection",
	SERVICE_REQUEST: "origin:plugins:service:request",
	SERVICE_DATA_READ: "origin:plugins:service:data-read",
	SERVICE_DATA_WRITE: "origin:plugins:service:data-write",
	SERVICE_READY_REPORT: "origin:plugins:service:ready-report",
	OFFSCREEN_CAPTURE: "origin:plugins:offscreen-capture",
	OFFSCREEN_RELEASE: "origin:plugins:offscreen-release",
	NETWORK_REQUEST: "origin:plugins:network:request",
	GATEWAY_REQUEST: "origin:plugins:gateway:request",
	STORAGE_LIST: "origin:plugins:storage:list",
	STORAGE_READ_FILE: "origin:plugins:storage:read-file",
	STORAGE_READ_SNAPSHOT: "origin:plugins:storage:read-snapshot",
	STORAGE_COMMIT: "origin:plugins:storage:commit",
	STORAGE_PUT_BLOB: "origin:plugins:storage:put-blob",
	STORAGE_PUT_BLOB_FROM_FILE: "origin:plugins:storage:put-blob-from-file",
	STORAGE_READ_BLOB: "origin:plugins:storage:read-blob",
	STORAGE_GET_BLOB_REF: "origin:plugins:storage:get-blob-ref",
	STORAGE_DELETE_BLOB: "origin:plugins:storage:delete-blob",
	SECRETS_GET: "origin:plugins:secrets:get",
	SECRETS_HAS: "origin:plugins:secrets:has",
	SECRETS_KEYS: "origin:plugins:secrets:keys",
	SECRETS_SET: "origin:plugins:secrets:set",
	SECRETS_DELETE: "origin:plugins:secrets:delete",
	SECRETS_CHANGED: "origin:plugins:secrets:changed",
} as const;

export const PLUGIN_CONTRIBUTION_CHANNELS = {
	HOST_READY: "origin:plugins:agent-contribution-host-ready",
	BEGIN_LOAD: "origin:plugins:agent-contributions-begin-load",
	COMMIT_LOAD: "origin:plugins:agent-contributions-commit-load",
	TOOL_REGISTER: "origin:plugins:agent-tool-register",
	TOOL_UNREGISTER: "origin:plugins:agent-tool-unregister",
	TOOL_REQUEST: "origin:plugins:agent-tool-request",
	TOOL_RESPONSE: "origin:plugins:agent-tool-response",
	HOOK_REGISTER: "origin:plugins:agent-hook-register",
	HOOK_UNREGISTER: "origin:plugins:agent-hook-unregister",
	HOOK_REQUEST: "origin:plugins:agent-hook-request",
	HOOK_RESPONSE: "origin:plugins:agent-hook-response",
	HANDLER_RELEASE: "origin:plugins:agent-handler-release",
	CLEAR: "origin:plugins:agent-contributions-clear",
	APP_ACTION_REGISTER: "origin:plugins:app-action-register",
	APP_ACTION_COMMIT: "origin:plugins:app-action-activation-commit",
	APP_ACTION_ABORT: "origin:plugins:app-action-activation-abort",
	APP_ACTION_UNREGISTER: "origin:plugins:app-action-unregister",
	APP_ACTION_REQUEST: "origin:plugins:app-action-request",
	APP_ACTION_CANCEL: "origin:plugins:app-action-cancel",
	APP_ACTION_RESPONSE: "origin:plugins:app-action-response",
	CONTINUATION_REGISTER: "origin:plugins:continuation-register",
	CONTINUATION_UNREGISTER: "origin:plugins:continuation-unregister",
	CONTINUATION_REQUEST: "origin:plugins:continuation-request",
	CONTINUATION_RESPONSE: "origin:plugins:continuation-response",
	SYSTEM_PROMPT_REGISTER: "origin:plugins:system-prompt-provider-register",
	SYSTEM_PROMPT_UNREGISTER: "origin:plugins:system-prompt-provider-unregister",
	SYSTEM_PROMPT_REQUEST: "origin:plugins:system-prompt-request",
	SYSTEM_PROMPT_RESPONSE: "origin:plugins:system-prompt-response",
	PLUGINS_CHANGED: "origin:plugins:changed",
} as const;

export const PLUGIN_MEDIA_CHANNELS = {
	REGISTER: "origin:plugins:media-provider-register",
	UNREGISTER: "origin:plugins:media-provider-unregister",
	REQUEST: "origin:plugins:media-provider-request",
	CHANGED: "origin:plugins:media-providers-changed",
	RESPONSE: "origin:plugins:media-provider-response",
	UPLOAD_INPUT: "origin:plugins:media-provider-input-upload",
	READ_INPUT: "origin:plugins:media-provider-input-read",
} as const;

export const PLUGIN_OCR_CHANNELS = {
	REGISTER: "origin:plugins:ocr-provider-register",
	UNREGISTER: "origin:plugins:ocr-provider-unregister",
	REQUEST: "origin:plugins:ocr-provider-request",
	RESPONSE: "origin:plugins:ocr-provider-response",
	CANCEL: "origin:plugins:ocr-provider-cancel",
	PROGRESS: "origin:plugins:ocr-provider-progress",
	GET_INPUT_URL: "origin:plugins:ocr-provider-input-url",
	UPLOAD_INPUT: "origin:plugins:ocr-provider-input-upload",
	CHANGED: "origin:plugins:ocr-providers-changed",
} as const;
