export { pendingEffects } from "./effects.js";
export {
	createCheckpointIdFactory,
	proposeOperationId,
} from "./ids.js";
export { MemoryCheckpointStore } from "./memory-store.js";
export type {
	CheckpointClock,
	CheckpointEffect,
	CheckpointEngine,
	CheckpointIdFactory,
	CheckpointIntentRecord,
	CheckpointStore,
	VerificationRunInput,
	VerificationRunner,
	WorkTreeDiff,
	WorkTreeDiffInput,
	WorkTreeLandInput,
	WorkTreeRestoreInput,
	WorkTreeVcs,
} from "./ports.js";
export {
	CheckpointReactor,
	type CheckpointReactorOptions,
} from "./reactor.js";
export {
	type ExecutionReceiptRecord,
	ExecutionReceiptSchema,
	isExecutionReceipt,
	isMainlineCheckpoint,
	isVerificationOutcome,
	type MainlineCheckpointRecord,
	MainlineCheckpointSchema,
	parseExecutionReceipt,
	parseMainlineCheckpoint,
	type VerificationOutcomeRecord,
} from "./schema.js";
export {
	allVerificationsPassed,
	canRequestRevert,
	canRerunVerification,
	createProposedCheckpoint,
	decideAfterFailedVerification,
	interruptRunningVerification,
	markFailed,
	markLanded,
	markReverted,
	markReverting,
	markVerificationRunning,
	markVerificationSettled,
	nextUnsettledVerification,
	resetVerificationForRerun,
} from "./state-machine.js";
export {
	boundCheckpointFailure,
	CHECKPOINT_RECORD_TYPE,
	CHECKPOINT_SCHEMA_VERSION,
	type CheckpointDecision,
	type CheckpointFailurePolicy,
	type CheckpointPhase,
	type CheckpointPolicy,
	type CheckpointProposeResult,
	type CheckpointVcsMode,
	type CheckpointVerificationState,
	type CheckpointVerificationStep,
	DEFAULT_CHECKPOINT_POLICY,
	EXECUTION_RECEIPT_RECORD_TYPE,
	EXECUTION_RECEIPT_SCHEMA_VERSION,
	type ExecutionReceipt,
	HOME_PROJECT_KEY,
	MAX_CHECKPOINT_FAILURE_BYTES,
	MAX_CHECKPOINT_INTENT_BYTES,
	MAX_CHECKPOINT_PATH_BYTES,
	MAX_CHECKPOINT_PATHS,
	MAX_PROJECT_CHECKPOINTS,
	type MainlineCheckpoint,
	type MainlineCommit,
	type ProposeCheckpointInput,
	type VerificationOutcome,
	verificationOutcomePassed,
} from "./types.js";
